enable_ansible_debug: false
# format: "http://<jumphost_ip>:40001"
nsx_image_webserver: "http://192.168.110.39:40001"

# NSX general network settings
mgmt_portgroup: 'ESXi-RegionA01-vDS-COMP'
dns_server: 192.168.110.10
dns_domain: corp.local.io
ntp_servers: time.vmware.com
default_gateway: 192.168.110.1
netmask: 255.255.255.0

# NSX manager cluster configs
nsx_manager_ips: 192.168.110.66 # Specify 1 or 3 values, comma separated
nsx_manager_username: admin
nsx_manager_password: Admin!23Admin # Min 12 chars, upper, lower, number, special digit
nsx_manager_hostname_prefix: "nsxt-mgr"
nsx_manager_root_pwd: Admin!23Admin
nsx_manager_cli_pwd: Admin!23Admin
nsx_manager_deployment_size: small
nsx_manager_deployment_ip_prefix_length: 23
nsx_manager_ssh_enabled: True

vcenter_ip: 192.168.110.22
vcenter_username: "Administrator@corp.local"
vcenter_password: "VMware1!"
vcenter_datacenter: RegionA01
vcenter_cluster: RegionA01-MGMT # management cluster
vcenter_datastore: iscsi
resource_reservation_off: true
# Compute manager credentials should be the same as above vCenter's if
# controllers and edges are to be on the same vCenter
compute_manager_username: "Administrator@corp.local"
compute_manager_password: "VMware1!"

edge_uplink_profile_vlan: 0 # For outbound uplink connection used by Edge, usually keep as 0
esxi_uplink_profile_vlan: 0 # For internal overlay connection used by Esxi hosts, usually trasnport VLAN ID
esx_available_vmnic: "vmnic1"

# Virtual Tunnel Endpoint network ip pool
vtep_ip_pool_cidr: 192.168.213.0/24
vtep_ip_pool_gateway: 192.168.213.1
vtep_ip_pool_start: 192.168.213.10
vtep_ip_pool_end: 192.168.213.200

# Tier 0 router
tier0_router_name: top-tier-gateway
tier0_uplink_port_ip: 192.168.100.44
tier0_uplink_port_ip_2: 192.168.100.45
tier0_uplink_port_subnet: 24
tier0_uplink_next_hop_ip: 192.168.100.1
tier0_ha_vip: 192.168.100.3

## Edge nodes
edge_ips: 192.168.110.67,192.168.110.68  # Comma separated based in number of required edges
edge_default_gateway: 192.168.110.1
edge_ip_prefix_length: 24
edge_hostname_prefix: nsx-t-edge
edge_transport_node_prefix: edge-transp-node
edge_cli_password: "Admin!23Admin"
edge_root_password: "Admin!23Admin"
edge_deployment_size: "small"            # Large recommended for PKS deployments
vc_datacenter_for_edge: RegionA01
vc_cluster_for_edge: RegionA01-MGMT
vc_datastore_for_edge: iscsi
vc_uplink_network_for_edge: "ESXi-RegionA01-vDS-COMP"
vc_overlay_network_for_edge: "VM-RegionA01-vDS-COMP"
vc_management_network_for_edge: "ESXi-RegionA01-vDS-COMP"

## ESX hosts
# Install NSX on vSphere clusters automatically
clusters_to_install_nsx: RegionA01-MGMT,RegionA01-K8s  # Comma separated
per_cluster_vlans: 0,0   # Every cluster specified above need a vlan

nsx_t_csr_request_spec: |
  csr_request:
    #common_name not required - would use nsx_t_manager_host_name
    org_name: Company            # EDIT
    org_unit: net-integ          # EDIT
    country: US                  # EDIT
    state: CA                    # EDIT
    city: SF                     # EDIT
    key_size: 2048               # Valid values: 2048 or 3072
    algorithm: RSA               # Valid values: RSA or DSA